trigger: none
  # branches:
  #   include:
  #     - master
  # paths:
  #   include:
  #     - /Terraform/Networking/Spoke-Prod/Spoke-Prod.tf
  #     - /Terraform/Networking/Spoke-Prod/variables.tf
  #     - /Terraform/Networking/Spoke-Prod/outputs.tf
  #     - /Terraform/Networking/Deployments/Network-Deployment/Spoke-Deploy/SpokeDeploy.tf
  #     - /Terraform/Networking/Deployments/Network-Deployment/Spoke-Deploy/variables.tf
  #     - /Terraform/Networking/Deployments/Network-Deployment/Spoke-Deploy/Spoke.tfvars

resources:
  pipelines:
  - pipeline: "Deploy Spoke VNETs"
    source: "Deploy Hub VNET"
    trigger: 
      branches:
      - master

pool:
  vmImage: "ubuntu-latest"

variables:
  - group: Terraform Pipeline Variables
  - group: Terraform Sensitive Variables
  - name: StateFile
    value: tf-statefile-spoke.tfstate

steps:
  - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
    displayName: "Install Terraform"
    inputs:
      terraformVersion: '0.13.3'
  
  - script: terraform version
    displayName: "Terraform Version"

  - script:  az login --service-principal -u $(application_id) -p $(SPNPassword) --tenant $(tenant_id)
    displayName: "Log Into Azure"

  - script: terraform init -backend-config=resource_group_name=$(sa-resource_group) -backend-config="storage_account_name=$(storage_account)" -backend-config="container_name=$(blob_storage)" -backend-config="access_key=$(StorageAccountAccessKey)" -backend-config="key=$(StateFile)"
    displayName: "Terraform Init"
    workingDirectory: $(System.DefaultWorkingDirectory)/Terraform/Networking/Deployments/Network-Deployment/Spoke-Deploy

  - script: terraform plan -var="client_id=$(application_id)" -var="client_secret=$(SPNPassword)" -var="tenant_id=$(tenant_id)" -var="subscription_id=$(subscription_id)" -var-file="Spoke.tfvars" -out="SpokeDeploy.plan"
    displayName: "Terraform Plan"
    workingDirectory: $(System.DefaultWorkingDirectory)/Terraform/Networking/Deployments/Network-Deployment/Spoke-Deploy

  - script: terraform apply SpokeDeploy.plan
    displayName: "Terraform Apply"
    workingDirectory: $(System.DefaultWorkingDirectory)/Terraform/Networking/Deployments/Network-Deployment/Spoke-Deploy
